[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/agflow/agstring"
  version = "1.9.0"

[[constraint]]
  name = "github.com/agflow/agnumber"
  version = "v0.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/thoas/go-funk"

[prune]
  go-tests = true
  unused-packages = true
