[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
